JAVA=javac

all : clientTCP.class serveurTCP.class servThread.class clientTCPReception.class Client.class Conv.class ConvReception.class Conversation.class Hote.class Popup.class

%.class : %.java
	$(JAVA) $^

clean :
	rm *.class
	
	
