JAVA=javac

all : clientTCP.class serveurTCP.class servThread.class clientTCPReception.class

clientTCP.class : clientTCP.java
	$(JAVA) $^

serveurTCP.class : serveurTCP.java
	$(JAVA) $^
	
servThread.class : servThread.java
	$(JAVA) $^
	
clientTCPReception.class : clientTCPReception.java
	$(JAVA) $^

clean :
	rm *.class
	
	
